version: 2.1

orbs:
  python: circleci/python@0.2.1


##################
# Job Definitions
##################

jobs:
  install-dependencies:
    working_directory: ~/workdir
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout

      - restore_cache:
          key: deps15-{{ checksum "Makefile" }}

      - run:
          name: BASH_ENV PATH
          command: echo "export PATH=$PATH:/home/circleci/.local/bin" >> $BASH_ENV

      - run:
          name: Install system requirements
          command: make install-system-deps

      - save_cache:
          key: deps15-{{ checksum "Makefile" }}
          paths:
            - /home/circleci/.local

      - restore_cache:
          keys:
            - deps15-{{ checksum "poetry.lock" }}-{{ checksum "Makefile" }}

      - run:
          name: Install dependencies
          command: |
            make poetry-setup


      - save_cache:
          key: deps15-{{ checksum "poetry.lock" }}-{{ checksum "Makefile" }}
          paths:
            - ".venv"

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - workdir
            - .local

  test:
    working_directory: ~/workdir
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: BASH_ENV PATH
          command: echo "export PATH=$PATH:/home/circleci/.local/bin" >> $BASH_ENV

      - run:
          name: Testing
          command: make unit-test
  
  deploy:
    working_directory: ~/workdir
    docker:
      - image: circleci/python:3.7.7
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: verify git tag vs. version
          command: make verify-version-tag

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = neuralspace" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      
      - run:
          name: create package
          command: make package-upload

############
# Workflows
############

workflows:
  version: 2
  build_test:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+.[0-9]+.[0-9]+[a-z]*/
            branches:
              ignore: /.*/
